### 对测试数据集如何归一化？？？
- 注意其中陷阱
- 测试数据是模拟真实环境
    - 真实环境可能无法得到所有测试数据的方差和均值：可能一次只需要测试一个样本，导致均值方差无统计意义
    - 对数据的归一化也是算法的一部分
![](测试数据集归一化方法.png)
- 由图可知道，要保存训练样本的均值和方差
- scikit-learn中的Scalar
![](归一化流程.png)


In [21]:
import numpy as np
from sklearn import datasets

In [22]:
iris = datasets.load_iris()
iris.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [23]:
X = iris.data
y = iris.target

In [7]:
X[:10,0]

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9])

In [24]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=666)
print(X_train.shape)
print(X_test.shape)

(120, 4)
(30, 4)


### sklearn 中的standardScalar

In [25]:
# 数据归一化  实质为数据预处理
from sklearn.preprocessing import StandardScaler

In [26]:
standardScalar = StandardScaler()

In [27]:
standardScalar.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [28]:
standardScalar.mean_

array([5.83416667, 3.08666667, 3.70833333, 1.17      ])

In [29]:
standardScalar.scale_   #分布范围，方差是描述分布范围的其中一种方式

array([0.81019502, 0.44327067, 1.76401924, 0.75317107])

In [30]:
X_train = standardScalar.transform(X_train)

In [31]:
X_test_standard = standardScalar.transform(X_test)

In [32]:
from sklearn.neighbors import KNeighborsClassifier
knn_clf = KNeighborsClassifier(n_neighbors=3)
knn_clf.fit(X_train,y_train)
knn_clf.score(X_test_standard,y_test)

1.0

In [33]:
knn_clf.score(X_test,y_test)

0.3333333333333333

### 作业：使用最值归一化对鸢尾花数据进行操作并训练