In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
iris = datasets.load_iris()
X = iris.data
y = iris.target

In [2]:
X.shape

(150, 4)

In [3]:
y.shape

(150,)

In [4]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [5]:
y = y.reshape(len(y),-1)

In [6]:
y

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
    

In [7]:
y.shape

(150, 1)

### split

In [57]:
"""
一种思路：将数据特征矩阵和标签合并，然后再统一打乱（暂未实现）
"""
#whole_data = np.concatenate([X,y],axis = 1)
whole_data = np.hstack([X,y])

In [59]:
"""
另一种思路，打乱下标（更简单）
"""
shuffle_indexes = np.random.permutation(len(X))
shuffle_indexes

array([ 52, 130, 118,  14, 134,  37,  20, 138, 110,   7,  91, 132,  98,
       133,  38, 139,  24,  54,  97,  11, 143,   3, 119, 115,  10,  76,
        19, 122, 145,  70, 114, 117, 149, 112,  30,  66,  79,  25,  45,
       124,  87,  78, 109, 111,  68, 137,  50,   1, 105, 100,  77, 136,
       101,  29,   6,  55,  90,  21,  58,  49,  59,  93,  67,  12, 102,
       128,  89,  56,  43,  44, 142, 147,  63, 129,  84,  53,  82,  60,
        88,  34, 107,  94,  48,  86, 126,   0,  74,  51,  65, 123,   9,
        40,  22,  15,  75,  16,  83,  73,  46, 108, 125, 141,  26, 146,
        64,  39, 104,  31,  47,  33,  99,  41,  13,  80, 135,  62,  69,
        72,   5,  28,   4,  96,  23,  81,  35, 140,  42,  32, 127,  92,
        61, 113,  18,  71, 116,  57,  36,  27,  17, 121, 120, 106,  95,
       103,  85,   2,   8, 131, 144, 148])

In [62]:
test_ratio = 0.2
test_size = int(len(X) * test_ratio)
test_size

30

In [65]:
train_indexes = shuffle_indexes[:len(X) - test_size]
test_indexes = shuffle_indexes[len(X) - test_size:]

In [69]:
# X_train = np.array([X[i] for i in train_indexes])
# y_train = np.array([y[i] for i in train_indexes])

# X_test = np.array([X[i] for i in test_indexes])
# y_test = np.array([y[i] for i in test_indexes])

X_train = X[train_indexes]
y_train = y[train_indexes]

X_test = X[test_indexes]
y_test = y[test_indexes]

In [73]:
print(X_train.shape)
print(y_train.shape)

print(X_test.shape)
print(y_test.shape)

(120, 4)
(120, 1)
(30, 4)
(30, 1)


In [5]:
from Machine_Learning.KNN.model_selection import train_test_split

In [6]:
X_train,X_test,y_train,y_test = train_test_split(X,y)

In [8]:
from Machine_Learning.KNN.kNN import KNNClassifier
kNNClassifier = KNNClassifier(k = 3)
kNNClassifier.fit(X_train,y_train)
y_predict = kNNClassifier.predict(X_test)
y_predict

array([2, 2, 2, 1, 0, 1, 1, 0, 1, 1, 1, 0, 2, 2, 2, 0, 1, 1, 2, 0, 0, 1,
       2, 1, 2, 0, 1, 2, 1, 1])

In [10]:
sum(y_predict == y_test)

29

In [13]:
acc = sum(y_predict == y_test) / len(y_test)
acc

0.9666666666666667

### scikit learn中的split

In [14]:
from sklearn.model_selection import train_test_split

In [16]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2)

In [17]:
print(X_train.shape)
print(y_train.shape)

print(X_test.shape)
print(y_test.shape)

(120, 4)
(120,)
(30, 4)
(30,)
