## numpy数据基础

In [3]:
%timeit list = [i**2 for i in range(1000)]

756 µs ± 130 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [5]:
import numpy as np

In [6]:
np.__version__

'1.16.5'

In [7]:
nparray = np.array([i for i in range(100)])
print(nparray)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [8]:
nparray.dtype

dtype('int32')

In [9]:
nparray[5] = 5.0

In [10]:
nparray.dtype  #类型转换，把5.0转换成了int类型

dtype('int32')

In [11]:
nparray2 = np.array([1,2,3.14])

In [12]:
nparray2.dtype

dtype('float64')

## 其他创建numpy数组的方法

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros(10).dtype

dtype('float64')

In [16]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
np.zeros(10,dtype=int).dtype

dtype('int32')

In [20]:
np.zeros(shape=(3,6),dtype=int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [21]:
np.ones(shape=(3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
np.full(shape=(2,3),fill_value=666)

array([[666, 666, 666],
       [666, 666, 666]])

### arange

In [24]:
[i for i in range(0,20,2)]  #前闭后开，步长为2

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [26]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [27]:
[i for i in range(0,20,0.2)]  

TypeError: 'float' object cannot be interpreted as an integer

In [28]:
np.arange(0,1,0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

### linspace

In [29]:
# 前闭后闭，意味[0,20]范围中取10个数，等差数列
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [30]:
np.linspace(0,20,11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

### random

In [32]:
np.random.randint(0,10)

7

In [33]:
# 前闭后开，生成10个元素的向量
np.random.randint(0,10,10)

array([5, 9, 8, 0, 6, 8, 4, 5, 8, 2])

In [34]:
np.random.randint(0,10,size=10)

array([5, 5, 2, 6, 1, 9, 4, 9, 6, 3])

In [35]:
np.random.randint(0,10,size=(2,5))

array([[3, 9, 3, 1, 3],
       [6, 6, 2, 0, 9]])

In [37]:
# 设置随机种子，如果种子一样，则生成的随机数一样，如当前和下一个cel里面的示例
np.random.seed(666)
np.random.randint(0,10,size=(2,5))

array([[2, 6, 9, 4, 3],
       [1, 0, 8, 7, 5]])

In [38]:
np.random.seed(666)
np.random.randint(0,10,size=(2,5))

array([[2, 6, 9, 4, 3],
       [1, 0, 8, 7, 5]])

In [39]:
np.random.random()

0.19289200304058374

In [40]:
np.random.random(12)

array([0.70084475, 0.29322811, 0.77447945, 0.00510884, 0.11285765,
       0.11095367, 0.24766823, 0.0232363 , 0.72732115, 0.34003494,
       0.19750316, 0.90917959])

In [41]:
np.random.random((3,5))

array([[0.97834699, 0.53280254, 0.25913185, 0.58381262, 0.32569065],
       [0.88889931, 0.62640453, 0.81887369, 0.54734542, 0.41671201],
       [0.74304719, 0.36959638, 0.07516654, 0.77519298, 0.21940924]])

In [44]:
# 符合正态分布的随机数
np.random.normal()

0.29655378389904696

In [45]:
# 指定均值和方差的正态分布随机数
np.random.normal(10,100)  # 均值为10，方差为100

6.873204963707662

In [47]:
np.random.normal(10,100,(2,3))  # 均值为10，方差为100

array([[161.814514  ,  17.72218828,   3.60086759],
       [104.59234072, 130.40910055, -35.12407353]])

In [53]:
#查询函数的文档
np.random.normal?

In [ ]:
help(np.random.normal)

### array的基础操作

In [57]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
X = np.arange(15).reshape(3,5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [60]:
# 维数
x.ndim

1

In [61]:
x.shape

(10,)

In [62]:
X.shape

(3, 5)

In [63]:
x.size

10

In [64]:
X.size

15

### 数据访问

In [65]:
x[1]

1

In [66]:
x[-1]

9

In [67]:
X[0][0]

0

In [69]:
X[0,0]# 更推荐

0

In [70]:
# 切片
x[:5]

array([0, 1, 2, 3, 4])

In [71]:
x[::2]

array([0, 2, 4, 6, 8])

In [72]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [73]:
X[:2,:3]#前两行，前三列

array([[0, 1, 2],
       [5, 6, 7]])

In [74]:
X[:2][:3]#错误！不是我们期望的结果

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [75]:
X[::-1,::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [76]:
#取一列：
X[:,0]

array([ 0,  5, 10])

In [83]:
subX = X[:2,:3]
print(subX)

subX[0,0]=100
print(subX)

[[0 1 2]
 [5 6 7]]
[[100   1   2]
 [  5   6   7]]


In [84]:
X  #X中的却也被修改了，所以，要用下面的办法

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [87]:
X[0][0] = 0
subX = X[:2,:3].copy()
subX

array([[0, 1, 2],
       [5, 6, 7]])

### reshape

In [88]:
x.shape

(10,)

In [89]:
x.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [90]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
A = x.reshape(2,5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [93]:
B = x.reshape(1,10)
B

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [95]:
x.reshape(10,-1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [96]:
x.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [97]:
x.reshape(3,-1)

ValueError: cannot reshape array of size 10 into shape (3,newaxis)

### 合并操作

In [99]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [100]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [105]:
A = np.array([
    [1,2,3],
    [4,5,6]
])

In [106]:
np.concatenate([A,A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [107]:
np.concatenate([A,A],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [109]:
np.vstack((x,y))

array([[1, 2, 3],
       [4, 5, 6]])

In [124]:
np.hstack((x,y))

array([1, 2, 3, 4, 5, 6])

In [3]:
import numpy as np
z = np.array([666,666,666])
z.reshape(1,-1)

array([[666, 666, 666]])

In [121]:
np.concatenate([A,z])

ValueError: all the input arrays must have same number of dimensions

In [122]:
np.concatenate([A,z.reshape(1,-1)])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

### 数据分割

In [125]:
x = np.arange(10)

In [129]:
x1,x2,x3 = np.split(x,[3,7])

In [128]:
x1

array([0, 1, 2])

In [130]:
x2

array([3, 4, 5, 6])

In [131]:
x3

array([7, 8, 9])

In [132]:
np.split(x,[5])

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [135]:
A = np.arange(16).reshape((4,4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [136]:
np.split(A,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [137]:
np.split(A,[2],axis = 1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [138]:
np.vsplit(A,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [139]:
np.hsplit(A,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [145]:
"""
数据分割的意义：

如果4x4的矩阵，前三列是特征矩阵，最后一列是标签向量
我们需要将它们分开
"""
X,y =np.split(A,[-1],axis = 1)
print(X)
print(y)

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]
[[ 3]
 [ 7]
 [11]
 [15]]


In [146]:
"""
这里y的维度不对，应该是一个向量
"""
y = y[:,0]
y

array([ 3,  7, 11, 15])

### numpy中的运算

In [4]:
import numpy as np
n = 10
L = np.arange(0,n)

In [5]:
L

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
2*L

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
# 原生list：
List = [i for i in range(10)]

In [8]:
List

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
2*List

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [11]:
n=1000000
L = [i for i in range(n)]

In [17]:
%%time
A=[]
for e in L:
    A.append(2*e)

Wall time: 330 ms


In [18]:
%%time
A = [2*e for e in L]

Wall time: 248 ms


In [20]:
%%time
L = np.arange(0,n)
L*2

Wall time: 13 ms


array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

###   上面方法比原生list效率高很多倍

### universal function

In [25]:
X= np.arange(0,15).reshape((3,5))
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [26]:
2*X

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [27]:
X+1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [28]:
X/2

array([[0. , 0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. , 4.5],
       [5. , 5.5, 6. , 6.5, 7. ]])

In [29]:
X//2

array([[0, 0, 1, 1, 2],
       [2, 3, 3, 4, 4],
       [5, 5, 6, 6, 7]], dtype=int32)

In [30]:
X**2

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]], dtype=int32)

In [31]:
X % 3

array([[0, 1, 2, 0, 1],
       [2, 0, 1, 2, 0],
       [1, 2, 0, 1, 2]], dtype=int32)

In [34]:
1 / X

D:\Tool\Ana\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[       inf, 1.        , 0.5       , 0.33333333, 0.25      ],
       [0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111],
       [0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857]])

In [35]:
np.abs(X)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [36]:
np.sin(X)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849],
       [-0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736]])

In [37]:
np.cos(X)

array([[ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362],
       [ 0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026],
       [-0.83907153,  0.0044257 ,  0.84385396,  0.90744678,  0.13673722]])

In [38]:
np.tan(X)

array([[ 0.00000000e+00,  1.55740772e+00, -2.18503986e+00,
        -1.42546543e-01,  1.15782128e+00],
       [-3.38051501e+00, -2.91006191e-01,  8.71447983e-01,
        -6.79971146e+00, -4.52315659e-01],
       [ 6.48360827e-01, -2.25950846e+02, -6.35859929e-01,
         4.63021133e-01,  7.24460662e+00]])

In [39]:
np.exp(X)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
        5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
        8.10308393e+03],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
        1.20260428e+06]])

In [40]:
np.power(3,X)

array([[      1,       3,       9,      27,      81],
       [    243,     729,    2187,    6561,   19683],
       [  59049,  177147,  531441, 1594323, 4782969]], dtype=int32)

In [41]:
np.log(X)# e为底数

D:\Tool\Ana\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([[      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436],
       [1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458],
       [2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733]])

In [42]:
np.log2(X)

D:\Tool\Ana\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log2
  """Entry point for launching an IPython kernel.


array([[      -inf, 0.        , 1.        , 1.5849625 , 2.        ],
       [2.32192809, 2.5849625 , 2.80735492, 3.        , 3.169925  ],
       [3.32192809, 3.45943162, 3.5849625 , 3.70043972, 3.80735492]])

### 矩阵运算

In [44]:
A = np.arange(4).reshape((2,2))
A

array([[0, 1],
       [2, 3]])

In [46]:
B = np.full((2,2),10)
B

array([[10, 10],
       [10, 10]])

In [47]:
A+B

array([[10, 11],
       [12, 13]])

In [48]:
A-B

array([[-10,  -9],
       [ -8,  -7]])

In [49]:
A*B # 对应元素相乘

array([[ 0, 10],
       [20, 30]])

In [51]:
A /B

array([[0. , 0.1],
       [0.2, 0.3]])

In [52]:
A.dot(B)# 矩阵乘法

array([[10, 10],
       [50, 50]])

In [53]:
A.T #转置矩阵

array([[0, 2],
       [1, 3]])

In [55]:
C = np.full((3,3),4)
C# 不能和A、B做运算

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

### 向量和矩阵的运算

In [58]:
v= np.array([1,2])
v

array([1, 2])

In [57]:
A

array([[0, 1],
       [2, 3]])

In [59]:
v+A

array([[1, 3],
       [3, 5]])

In [60]:
np.vstack([v]*A.shape[0])

array([[1, 2],
       [1, 2]])

In [61]:
np.vstack([v]*A.shape[0])+A

array([[1, 3],
       [3, 5]])

In [62]:
np.tile(v,(2,1))

array([[1, 2],
       [1, 2]])

In [63]:
np.tile(v,(2,1))+A

array([[1, 3],
       [3, 5]])

In [65]:
v

array([1, 2])

In [66]:
A

array([[0, 1],
       [2, 3]])

In [67]:
v*A

array([[0, 2],
       [2, 6]])

In [68]:
A.dot(v)#numpy 智能识别

array([2, 8])

In [69]:
v.dot(A)

array([4, 7])

### 矩阵的逆

In [70]:
A

array([[0, 1],
       [2, 3]])

In [71]:
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [72]:
inverse = np.linalg.inv(A)

In [73]:
A.dot(inverse)

array([[1., 0.],
       [0., 1.]])

In [74]:
inverse.dot(A)

array([[1., 0.],
       [0., 1.]])

In [75]:
# 方阵才能求逆矩阵

In [76]:
# 针对非方阵，可以求伪逆
np.linalg.pinv(A)

array([[-1.50000000e+00,  5.00000000e-01],
       [ 1.00000000e+00,  5.55111512e-17]])

###  聚合操作

In [78]:
import numpy as np

L = np.random.random(100)
L

array([0.03528801, 0.89799933, 0.57964211, 0.94008376, 0.45038436,
       0.48738391, 0.73732084, 0.89529226, 0.99260736, 0.95380865,
       0.73565182, 0.79881795, 0.53073596, 0.94703183, 0.15303294,
       0.14669956, 0.9856959 , 0.62720057, 0.24943948, 0.93696016,
       0.43919339, 0.79105124, 0.38042132, 0.24384992, 0.90291811,
       0.47686006, 0.86140026, 0.73420182, 0.28351668, 0.92451737,
       0.49397227, 0.77701771, 0.97797649, 0.12712999, 0.13126908,
       0.06884352, 0.16943918, 0.04057013, 0.72174649, 0.29766619,
       0.16352414, 0.27641323, 0.90305779, 0.97554598, 0.60609991,
       0.05805842, 0.00375396, 0.88976753, 0.59658052, 0.67210697,
       0.95039853, 0.48163301, 0.55753762, 0.79285295, 0.56191061,
       0.76687851, 0.43490538, 0.17201458, 0.90006854, 0.68361142,
       0.0710506 , 0.34111386, 0.48825383, 0.27825768, 0.98863237,
       0.70439812, 0.04171681, 0.86245602, 0.36857027, 0.75274256,
       0.32792611, 0.5987088 , 0.11334579, 0.4690669 , 0.26181

In [79]:
sum(L)

52.473214546375495

In [80]:
np.sum(L)# 也是效率的区别

52.47321454637545

In [83]:
np.min(L)

0.0037539631124889894

In [84]:
np.max(L)# 推荐使用这种方法

0.9926073636266194

In [85]:
L.min()

0.0037539631124889894

In [86]:
L.max()

0.9926073636266194

In [87]:
X = np.arange(0,16).reshape(4,-1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [88]:
np.min(X)

0

In [89]:
np.max(X)

15

In [90]:
np.sum(X)

120

In [91]:
np.sum(X,axis=1)

array([ 6, 22, 38, 54])

In [92]:
np.sum(X,axis=0)

array([24, 28, 32, 36])

In [93]:
np.prod(X)#所有元素的乘积

0

In [94]:
np.prod(X+1)

2004189184

In [96]:
np.mean(X)

7.5

In [97]:
np.median(X)

7.5

In [101]:
np.percentile(X,q=80)#q是百分位数，表示求超过数据80%的值

12.0

In [102]:
np.percentile(X,q=50)#q是百分位数，表示求超过数据50%的值

7.5

In [103]:
np.percentile(X,q=100)#q是百分位数，表示求超过数据100%的值

15.0

In [104]:
for percent in [0,25,50,75,100]:
    print(np.percentile(X,q=percent))

0.0
3.75
7.5
11.25
15.0


In [105]:
np.var(X)#方差

21.25

In [106]:
np.std(X)#标准差

4.6097722286464435

In [107]:
X = np.random.normal(0,1,size=1000000)

In [108]:
X.mean()

0.0009615605420743717

In [109]:
X.std()

0.9999093286165341

### 索引

In [110]:
np.min(X)

-5.309608125200176

In [111]:
np.argmin(X)

96075

In [112]:
X[96075]

-5.309608125200176

In [113]:
np.argmax(X)

356323

In [114]:
X[356323]

4.77337382828227

In [115]:
np.max(X)

4.77337382828227

### 排序和使用索引

In [117]:
X = np.arange(0,16)
X

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [119]:
np.random.shuffle(X)
X

array([14,  6, 11,  1,  3,  9,  0, 15,  4, 12, 13,  7,  8,  5,  2, 10])

In [120]:
np.sort(X)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [122]:
X

array([14,  6, 11,  1,  3,  9,  0, 15,  4, 12, 13,  7,  8,  5,  2, 10])

In [124]:
X.sort()
X

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [127]:
X = np.random.randint(10,size=(4,4))
X

array([[2, 7, 4, 2],
       [0, 6, 7, 6],
       [3, 1, 7, 2],
       [6, 2, 7, 1]])

In [128]:
np.sort(X)

array([[2, 2, 4, 7],
       [0, 6, 6, 7],
       [1, 2, 3, 7],
       [1, 2, 6, 7]])

In [129]:
np.sort(X,axis=0)

array([[0, 1, 4, 1],
       [2, 2, 7, 2],
       [3, 6, 7, 2],
       [6, 7, 7, 6]])

In [130]:
np.sort(X,axis=1)

array([[2, 2, 4, 7],
       [0, 6, 6, 7],
       [1, 2, 3, 7],
       [1, 2, 6, 7]])

In [132]:
x = np.arange(0,16)
np.random.shuffle(x)
x

array([10,  6,  0,  7,  1, 13, 14, 12,  8, 15,  2,  3,  9,  4,  5, 11])

In [133]:
np.argsort(x)

array([ 2,  4, 10, 11, 13, 14,  1,  3,  8, 12,  0, 15,  7,  5,  6,  9],
      dtype=int64)

In [135]:
sort_x = x[np.argsort(x)]
sort_x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [136]:
np.partition(x,3)

array([ 1,  2,  0,  3,  7, 10,  4,  6,  8,  9,  5, 11, 15, 14, 13, 12])

In [137]:
np.argpartition(x,3)

array([ 4, 10,  2, 11,  3,  0, 13,  1,  8, 12, 14, 15,  9,  6,  5,  7],
      dtype=int64)