### Fancy Indexing

In [1]:
import numpy as np

x= np.arange(0,16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [2]:
x[3]

3

In [3]:
x[3:10]

array([3, 4, 5, 6, 7, 8, 9])

In [4]:
x[3:10:2]

array([3, 5, 7, 9])

In [5]:
index = [3,5,8]
x[index]

array([3, 5, 8])

In [7]:
index = np.array([[0,2],
                 [1,3]])
x[index]

array([[0, 2],
       [1, 3]])

In [9]:
X = x.reshape(4,-1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [10]:
row = np.array([0,1,2])
col = np.array([1,2,3])
X[row,col]

array([ 1,  6, 11])

In [11]:
X[0,col]

array([1, 2, 3])

In [12]:
X[:2,col]

array([[1, 2, 3],
       [5, 6, 7]])

In [13]:
col = [True,False,True,True]
X[:,col]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15]])

### numpy的比较

In [14]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [15]:
x<3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [16]:
x[x<3]

array([0, 1, 2])

In [17]:
np.sum(x<=3)

4

In [19]:
np.count_nonzero(x<=3)

4

In [20]:
np.any(x==0)

True

In [21]:
np.any(x<0)

False

In [22]:
np.all(x>=0)

True

In [23]:
np.all(x>0)

False

In [24]:
np.sum(x%2==0)

8

In [25]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [27]:
np.sum(X%2==0,axis = 0)

array([4, 0, 4, 0])

In [28]:
np.sum(X%2==0,axis = 1)

array([2, 2, 2, 2])

In [29]:
np.sum(X>0,axis = 0)

array([3, 4, 4, 4])

In [30]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [34]:
np.sum((x > 3) & (x < 10)) #相当于两个bool变量做与运算

6

In [35]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [36]:
X[X[:,3] % 3 == 0, :] #找出X中符合1最后列能被3整除的所有行

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

#### pandas主要做预处理，处理完的数据转化成numpy矩阵，再交给sklearn进行学习